### ISSUE TITLE
Cannot load pre-trained model

### ISSUE THREAD

**Issue by tranquangchung** [Maelic/SGG-Benchmark#10]
Thank you for sharing this useful project. However, when I use the file "demo/SGDET_on_cutom_images.ipynb" with the following setting. The model cannot load the pre-trained model. So could you help me to fix this problem?  @Maelic 

config_path = "configs/VG150/e2e_relation_X_101_32_8_FPN_1x.yaml"
dict_path = "../datasets/vg/VG-SGG-dicts-with-attri.json"
weights_path = "pretrained/upload_causal_motif_sgdet/model_0028000.pth"

RuntimeError: Error(s) in loading state_dict for GeneralizedRCNN:
size mismatch for roi_heads.relation.predictor.context_layer.untreated_dcd_feat: copying a param with shape torch.Size([4936]) from checkpoint, the shape in current model is torch.Size([5248]).
size mismatch for roi_heads.relation.predictor.context_layer.untreated_obj_feat: copying a param with shape torch.Size([4424]) from checkpoint, the shape in current model is torch.Size([4736]).
size mismatch for roi_heads.relation.predictor.context_layer.untreated_edg_feat: copying a param with shape torch.Size([4296]) from checkpoint, the shape in current model is torch.Size([4608]).
size mismatch for roi_heads.relation.predictor.context_layer.obj_embed1.weight: copying a param with shape torch.Size([151, 200]) from checkpoint, the shape in current model is torch.Size([151, 512]).
size mismatch for roi_heads.relation.predictor.context_layer.obj_embed2.weight: copying a param with shape torch.Size([151, 200]) from checkpoint, the shape in current model is torch.Size([151, 512]).
size mismatch for roi_heads.relation.predictor.context_layer.obj_ctx_rnn.weight_ih_l0: copying a param with shape torch.Size([2048, 4424]) from checkpoint, the shape in current model is torch.Size([2048, 4736]).
size mismatch for roi_heads.relation.predictor.context_layer.obj_ctx_rnn.weight_ih_l0_reverse: copying a param with shape torch.Size([2048, 4424]) from checkpoint, the shape in current model is torch.Size([2048, 4736]).
size mismatch for roi_heads.relation.predictor.context_layer.edge_ctx_rnn.weight_ih_l0: copying a param with shape torch.Size([2048, 4808]) from checkpoint, the shape in current model is torch.Size([2048, 5120]).
size mismatch for roi_heads.relation.predictor.context_layer.edge_ctx_rnn.weight_ih_l0_reverse: copying a param with shape torch.Size([2048, 4808]) from checkpoint, the shape in current model is torch.Size([2048, 5120]).
size mismatch for roi_heads.relation.predictor.context_layer.decoder_rnn.obj_embed.weight: copying a param with shape torch.Size([152, 200]) from checkpoint, the shape in current model is torch.Size([152, 512]).
size mismatch for roi_heads.relation.predictor.context_layer.decoder_rnn.input_linearity.weight: copying a param with shape torch.Size([3072, 5136]) from checkpoint, the shape in current model is torch.Size([3072, 5760]).

**Comment by Maelic** [comment]
Please change the keys `TEXT_EMBEDDING` and `EMBED_DIM` in the configs/VG150/e2e_relation_X_101_32_8_FPN_1x.yaml file as follows:
```
TEXT_EMBEDDING: glove.6B
EMBED_DIM: 200
```

And it should work
