### ISSUE TITLE
pytorch 

### ISSUE THREAD

**Issue by Maritime-Moon** [Maelic/SGG-Benchmark#22]
Which version of the pytorch framework do you use?

**Comment by Maelic** [comment]
Hi, I am using Pytorch 2.2.1 but any recent version of Pytorch should work (probably above 1.11 if you want to be sure).

**Comment by Maritime-Moon** [comment]
So how do you deal with the dependency of the clip library?

**Comment by Maelic** [comment]
For the clip library, you should install it following this repository:
[https://github.com/ultralytics/CLIP](https://github.com/ultralytics/CLIP)

I haven't tested for every pytorch version but it should work with 1.7+, I fyou have any trouble you can post on issue on this other repo.

**Comment by Maelic** [comment]
Something like ``pip install git+https://github.com/openai/CLIP.git`` should work
