### ISSUE TITLE
yolov8m evalution？

### ISSUE THREAD

**Issue by Bobbypower** [Maelic/SGG-Benchmark#27]
"Thank you for the great work on the SGG project. While using the YOLOv8m model from the model zoo with the indoorvg dataset, I encountered an issue during validation—no relationship predictions are being generated. However, when I use Faster R-CNN, everything works fine. I'm unsure why this is happening during the model validation phase, as it seems like the relationship predictions are completely missing."

Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.236
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.406
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.243
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.083
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.206
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.322
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.279
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.353
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.356
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.141
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.326
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.421
Evaluating: 100%|█████████████████████████████████████████████████| 733/733 [00:00<00:00, 14322.03it/s]
2024-09-05 15:57:06.833 | INFO     | sgg_benchmark.data.datasets.evaluation.vg.vg_eval:do_vg_evaluation:174 -
====================================================================================================    
Detection evaluation mAp=0.4056
====================================================================================================    
SGG eval:     R @ 20: nan;     R @ 50: nan;     R @ 100: nan;  for mode=sgdet, type=Recall (Main).      
SGG eval:     IR @ 5: nan;     IR @ 10: nan;     IR @ 20: nan;     IR @ 50: nan;     IR @ 100: nan;  for mode=sgdet, type=Informative Recall.
SGG eval:    mR @ 20: 0.0000;    mR @ 50: 0.0000;    mR @ 100: 0.0000;  for mode=sgdet, type=Mean Recall.
----------------------- Details ------------------------
(above:0.0000) (against:0.0000) (at:0.0000) (attached to:0.0000) (behind:0.0000) (between:0.0000) (carrying:0.0000) (covering:0.0000) (cutting:0.0000) (drinking:0.0000) (eating:0.0000) (filled with:0.0000) (for:0.0000) (hanging from:0.0000) (has:0.0000) (holding:0.0000) (in:0.0000) (in front of:0.0000) (laying on:0.0000) (looking at:0.0000) (lying on:0.0000) (mounted on:0.0000) (near:0.0000) (of:0.0000) (on:0.0000) (playing with:0.0000) (reading:0.0000) (sitting at:0.0000) (sitting on:0.0000) (standing on:0.0000) (taking:0.0000) (talking on:0.0000) (under:0.0000) (using:0.0000) (watching:0.0000) (wearing:0.0000) (with:0.0000) 
--------------------------------------------------------
SGG eval:     F1 @ 20: 0.0000;     F1 @ 50: 0.0000;     F1 @ 100: 0.0000;  for mode=sgdet, type=F1.

**Comment by Bobbypower** [comment]
To clarify, it is during the entire training period, not just the pre-val  stage.
Has anyone encountered this issue?

**Comment by Maelic** [comment]
Hello, can you share your training/validation settings with me? I will need the .yaml file you are using and the training arguments.

**Comment by Bobbypower** [comment]
> Hello, can you share your training/validation settings with me? I will need the .yaml file you are using and the training arguments.

Hello, thank you for your response. Actually, I used the following command from the `TRAINING` file in the project:

```bash
CUDA_VISIBLE_DEVICES=θ python tools/relation_train_net.py --save-best --task sgdet --config-file "configs/IndoorVG/e2e_relation_yolov8.yaml" MODEL.ROI_RELATION_HEAD.PREDICTOR CausalAnalysisPredictor MODEL.ROI_RELATION_HEAD.CAUSAL.EFFECT_TYPE TDE MODEL.ROI_RELATION_HEAD.CAUSAL.FUSION_TYPE sum MODEL.ROI_RELATION_HEAD.CAUSAL.CONTEXT_LAYER cross_att SOLVER.IMS_PER_BATCH 8 TEST.IMS_PER_BATCH 8 DTYPE "float16" SOLVER.PRE_VAL False GLOVE_DIR /home/maelic/glove OUTPUT_DIR ./checkpoints/checkpointsIndoorVG4/SGDET
```

The configuration file `e2e_relation_yolov8.yaml` was also used, but I only modified the `OUTPUT_DIR`. The model I used is `yolov8m_indoorvg.pt` from the model zoo. I also tested `IndoorVG FASTRCNN`, and it works fine.

**Comment by Bobbypower** [comment]
I only modified some path-related values in the `configs/IndoorVG/e2e_relation_yolov8.yaml` file; everything else remains unchanged. However, I feel that the model isn't producing valid outputs during the validation and inference stages. As a new graduate student with a limited foundation, I carefully reviewed the code related to model construction but didn't find anything suspicious. Thank you for taking the time to respond to me.
