### ISSUE TITLE
yolov8+swin_transformerv2  about parameters problem

### ISSUE THREAD

**Issue by heavens77543** [Maelic/SGG-Benchmark#29]
The model（yolov8n+swin_transformerv2） about 800 million parameters but another model (yolov8n) about 300,000 parameters.Why are the model（yolov8n+swin_transformerv2） parameters so large？
Thanks！

**Comment by heavens77543** [comment]
The model（yolov8n+swin_transformerv2）  about 800 million parameters but another model (yolov8n)  about 300,000 parameters.Why are the model（yolov8n+swin_transformerv2） parameters so large？
Thanks！

**Comment by Maelic** [comment]
Hello, I am not using swin transformersv2 in this codebase so I don't know the parameters count of this model.
But yolov8n is 3.2M parameters, not 300,000, see [https://docs.ultralytics.com/models/yolov8/#performance-metrics](https://docs.ultralytics.com/models/yolov8/#performance-metrics).
