### ISSUE TITLE
ImportError: cannot import name 'Dataset' from 'datasets' (unknown location)

### ISSUE THREAD

**Issue by Catchip** [Maelic/SGG-Benchmark#30]
After I installed SGG-Benchmark according to the requirements in install.md, I encountered an error the first time I tried to pre-train Faster R-CNN following the example command. I also tried other tasks, such as training SGG using pre-trained YOLOv8, but the same error still occurred.

`  File "D:\miniforge\envs\scene_graph_benchmark\Lib\site-packages\sentence_transformers\SentenceTransformer.py", line 27, in <module>
    from sentence_transformers.model_card import SentenceTransformerModelCardData, generate_model_card
  File "D:\miniforge\envs\scene_graph_benchmark\Lib\site-packages\sentence_transformers\model_card.py", line 33, in <module>
    from datasets import Dataset, DatasetDict, Value
ImportError: cannot import name 'Dataset' from 'datasets' (unknown location)`

Then I tried manually importing the datasets to see if I could identify the issue. 

`Python 3.11.9 | packaged by Anaconda, Inc. | (main, Apr 19 2024, 16:40:41) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import datasets
>>> dir(datasets)
['__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__']
>>> datasets.__path__
_NamespacePath(['E:\\projects\\SGG-Benchmark\\datasets', 'e:\\projects\\sgg-benchmark\\datasets'])
>>>`

Any Idea about this error?

**Comment by Maelic** [comment]
Hi, this seems to be an issue with your install of the SentenceTransformer library, you can post an issue on their github or search for a similar problem. It seems that it is not directly related to my codebase.

If you're unable to fix this problem, you can comment the lines [https://github.com/Maelic/SGG-Benchmark/blob/73c2ecbc54b2f5ddff834991ce905eae1590e5b2/sgg_benchmark/data/datasets/evaluation/vg/sgg_eval.py#L11](https://github.com/Maelic/SGG-Benchmark/blob/73c2ecbc54b2f5ddff834991ce905eae1590e5b2/sgg_benchmark/data/datasets/evaluation/vg/sgg_eval.py#L11)

and

[https://github.com/Maelic/SGG-Benchmark/blob/73c2ecbc54b2f5ddff834991ce905eae1590e5b2/sgg_benchmark/modeling/roi_heads/relation_head/loss/loss.py#L17](https://github.com/Maelic/SGG-Benchmark/blob/73c2ecbc54b2f5ddff834991ce905eae1590e5b2/sgg_benchmark/modeling/roi_heads/relation_head/loss/loss.py#L17)

and you should have no problem running the codebase, the SentenceTransformer library is actually not a requirement of the codebase.

**Comment by Catchip** [comment]
Thanks,  I have tried the second way(just comment the lines) and it works
