### ISSUE TITLE
Almost Unusable Faster R-CNN Pre-training

### ISSUE THREAD

**Issue by afiff2** [Maelic/SGG-Benchmark#31]
I have encountered several issues while attempting to use Faster R-CNN pre-training. The problems include, but are not limited to, the following:

Configuration File Adjustments:
In the config file, the setting INPUT: `MIN_SIZE_TRAIN:(600,)` should be modified to `MIN_SIZE_TRAIN: 600`.
In the `MODEL: BACKBONE: section, CONV_BODY: "R-101-FPN"` should be changed to `TYPE: "R-101-FPN"`.

Modifications in detector_pretrain_net.py:

The following code block:
`if args.use_wandb:
    run_name = cfg.OUTPUT_DIR.split('/')[-1]
    if args.distributed:
        wandb.init(project="scene-graph-benchmark", entity="maelic", group="DDP", name=run_name, config=cfg)
    wandb.init(project="scene-graph-benchmark", entity="maelic", name=run_name, config=cfg)
    use_wandb = True`
   should be updated to include:
   `else:
    use_wandb = False`
    
Changes in paths_catalog.py:
Comment out:
`for k, v in args.items():
    args[k] = os.path.join(data_dir, v)`
    
Due to a lack of code management, I am uncertain whether these are all the modifications I made, and whether the training process will function correctly after these changes.

**Comment by Maelic** [comment]
Hello, you can use [this config file](https://github.com/Maelic/SGG-Benchmark/blob/main/configs/VG150/e2e_relation_X_101_32_8_FPN_1x.yaml) if you want to train a faster-rcnn for the VG150 dataset.

By the way, please be kind when posting issues on Github, I am working on this codebase alone in my free time and I am providing it entirely for free for the community. I also mentioned in the readme that this codebase is highly experimental. Right now I don't have a lot of time to maintain it properly, however Github is also a place where people can contribute, so if you find mistakes you can create a pull request and I would be happy to merge it.

**Comment by Maelic** [comment]
Yes the last part came out a bit rude to be honest ah ah
But it's ok we're cool now :)
