### ISSUE TITLE
Configs for SQUAT

### ISSUE THREAD

**Issue by tutuzeraa** [Maelic/SGG-Benchmark#38]
Hello! Very interesting work and repo :)

I'm interested in reproducing the SQUAT model. But, it was not clear for me how can i use the SQUAT relation head for training ...
It should be `MODEL.ROI_RELATION_HEAD.PREDICTOR SquatPredictor`, right?

Also, could you please provide the config files that you used for training/evaluating SQUAT? Is possible that I take the configs from the original work and use in the benchmark or that would require major changes?

Thanks for your time

**Comment by Maelic** [comment]
Hello! I appreciate your interest in my work!
Yes you can use the SquatPredictor for training the Squat model. My config for this model is similar to the default one [in here](https://github.com/Maelic/SGG-Benchmark/blob/286e1c14e26e653ac51811391b81dc2cdd136d23/sgg_benchmark/config/defaults.py#L330). However, depending on which dataset you want to train you may have to adjust the ```RHO``` and ```BETA``` values. To do so, I would recommend you to follow [my hyperparameter tunning method](https://github.com/Maelic/SGG-Benchmark/tree/main?tab=readme-ov-file#hyperparameters-tuning), specifically changing the ```model_config``` to the ```squat_config``` in the search space [here](https://github.com/Maelic/SGG-Benchmark/blob/286e1c14e26e653ac51811391b81dc2cdd136d23/tools/hyper_param_tuning.py#L331).
Hope this helps and happy coding :)

**Comment by tutuzeraa** [comment]
Thank you!
