### ISSUE TITLE
REACT checkpoint release

### ISSUE THREAD

**Issue by Catchip** [Maelic/SGG-Benchmark#44]
Impressive work! Do you have any plans to release the REACT checkpoints?

**Comment by Maelic** [comment]
Yes soon, stay tuned!

**Comment by Maelic** [comment]
Hi, I just released the first weights for the VG150 dataset, please have a look in [MODEL_ZOO.md](https://github.com/Maelic/SGG-Benchmark/blob/main/MODEL_ZOO.md).
Other weights will follow.
