### ISSUE TITLE
Out of memory error when training with yolov8 checkpoint

### ISSUE THREAD

**Issue by A11en4z** [Maelic/SGG-Benchmark#47]
thank you for your outstanding work on this project! I am very interested in your work and trying to implement the SGG task on a dataset of my own.
I tried the Fasterrcnn checkpoint and the yolov8 checkpoint respectively, and tried to reduce TSET.IMS_PER_BATCH to 1 , but both suffered Out of memory issues during the initial evaluation phase.
My GPU is an RTX 3080x2(20GB) 
My training instructions are: python /tools/relation_train_net.py --task predcls --save-best --config-file /e2e_relation_yolov8m.yaml MODEL.ROI_RELATION_HEAD. PREDICTOR MotifPredictor SOLVER.IMS_PER_BATCH 4 TEST.IMS_PER_BATCH 1 DTYPE “float16” 
![image](https://github.com/user-attachments/assets/a8b03ca0-5514-4738-b006-50e5e605fafb)
I have read on other issue that the GPU you are using is A6000 (42 GB), would like to ask you what is the actual footprint during training? Should I get a different card with more memory or is there any way to reduce the memory use?

-------------------
When i change my GPU to VGPU(32GB ),it was even worse 
here is my log :
2024-12-25 21:24:12.371 | INFO     | sgg_benchmark.utils.logger:logger_step:15 - #################### Step 6: Building dataloader ####################
2024-12-25 21:24:12.371 | INFO     | __main__:train:204 - Validate before training
2024-12-25 21:24:12.372 | INFO     | sgg_benchmark.engine.inference:inference:263 - Start evaluation on VG150_val dataset(1310 images).
 52%|_____________________________________________                                         | 682/1310 [00:26<00:24, 25.52it/s]
Traceback (most recent call last):
  File "/root/autodl-tmp/SGG-Benchmark/tools/relation_train_net.py", line 492, in <module>
    main()
  File "/root/autodl-tmp/SGG-Benchmark/tools/relation_train_net.py", line 471, in main
    model, best_checkpoint = train(
                             ^^^^^^
  File "/root/autodl-tmp/SGG-Benchmark/tools/relation_train_net.py", line 205, in train
    run_val(cfg, model, val_data_loaders, args['distributed'], logger, device=device)
  File "/root/autodl-tmp/SGG-Benchmark/tools/relation_train_net.py", line 324, in run_val
    dataset_result = inference(
                     ^^^^^^^^^^
  File "/root/autodl-tmp/SGG-Benchmark/sgg_benchmark/engine/inference.py", line 273, in inference
    predictions, timings, timings2 = compute_on_dataset(model, data_loader, device, synchronize_gather=cfg.TEST.RELATION.SYNC_GATHER, timer=True, silence=silence, informative=False)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/autodl-tmp/SGG-Benchmark/sgg_benchmark/engine/inference.py", line 48, in compute_on_dataset
    output = model(images.to(device), targets)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/sgg/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/sgg/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/autodl-tmp/SGG-Benchmark/sgg_benchmark/modeling/detector/generalized_yolo.py", line 82, in forward
    x, result, detector_losses = self.roi_heads(features, proposals, targets, logger, targets)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/sgg/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/sgg/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/autodl-tmp/SGG-Benchmark/sgg_benchmark/modeling/roi_heads/roi_heads.py", line 53, in forward
    x, detections, loss_relation = self.relation(features, detections, targets, logger)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/sgg/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/sgg/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/autodl-tmp/SGG-Benchmark/sgg_benchmark/modeling/roi_heads/relation_head/relation_head.py", line 89, in forward
    union_features = self.union_feature_extractor(features, proposals, rel_pair_idxs)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/sgg/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/sgg/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/autodl-tmp/SGG-Benchmark/sgg_benchmark/modeling/roi_heads/relation_head/roi_relation_feature_extractors.py", line 63, in forward
    head_proposal = proposal[rel_pair_idx[:, 0]]
                    ~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "/root/autodl-tmp/SGG-Benchmark/sgg_benchmark/structures/bounding_box.py", line 231, in __getitem__
    bbox.add_field(k, v[item][:,item], is_triplet=True)
                      ~~~~~~~^^^^^^^^
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 75.71 GiB. GPU 0 has a total capacty of 31.50 GiB of which 30.26 GiB is free. Including non-PyTorch memory, this process has 0 bytes memory in use. Of the allocated memory 520.48 MiB is allocated by PyTorch, and 381.52 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by A11en4z** [comment]
I think I may have found the cause, I printed len(rel_pair_idx) and found that len(rel_pair_idx)=100806 before the error was reported, this may be caused by the fact that the image has no GT relationship labeling

**Comment by Maelic** [comment]
If you have rel_pair_idx=100806 with batch size 1 it means that you are predicting more than 100k relations for a single image, which indeed may blow up your memory. There could be 2 reasons for that: 
* 1. you didn't correctly limit the number of proposals generated with the `MODEL.ROI_HEADS.DETECTIONS_PER_IMG` variable (do not make it higher than 100)
* 2. you have a groundtruth image with too many annotations (more than 300 objects)

The number of relations predicted will be proportional to the square of the number of objects (i.e. len(rel_pair_idx) = m^2 for m number of bounding boxes).

**Comment by A11en4z** [comment]
> The number of relations predicted will be proportional to the square of the number of objects (i.e. len(rel_pair_idx) = m^2 for m number of bounding boxes).

Thank you very much for your reply! I have examined my dataset and found that 3 of the images contain more than 400 boat-type dense targets, and I am going to manually remove these three images.
Also, is there any possible way to cope with this type of dense small target relationship prediction? My initial thought is that I could slice these images in more detail.But for now I'm going to leave them alone.

**Comment by Maelic** [comment]
There is [this work](https://openaccess.thecvf.com/content/CVPR2022/papers/Teng_Structured_Sparse_R-CNN_for_Direct_Scene_Graph_Generation_CVPR_2022_paper.pdf), [this work](https://arxiv.org/pdf/2112.12970) and [this work](https://openaccess.thecvf.com/content/CVPR2024/html/Im_EGTR_Extracting_Graph_from_Transformer_for_Scene_Graph_Generation_CVPR_2024_paper.html) that tackled the challenge of dense prediction by proposing to compute a "relatedness" or "connectedness" score to prune pairs that are unlikely to have a relation, before the relation prediction stage. It generates a sparse set of pairs that can also run faster because as I explained [in my work](https://arxiv.org/abs/2405.16116), the quadratic complexity of relation prediction is one of the major bottlenecks for real-time SGG. 
However, generating sparse proposals was not the first aim of my work so I didn't implement it here, but you could probably try it on your own to solve your problem.

**Comment by A11en4z** [comment]
> There is [this work](https://openaccess.thecvf.com/content/CVPR2022/papers/Teng_Structured_Sparse_R-CNN_for_Direct_Scene_Graph_Generation_CVPR_2022_paper.pdf), [this work](https://arxiv.org/pdf/2112.12970) and [this work](https://openaccess.thecvf.com/content/CVPR2024/html/Im_EGTR_Extracting_Graph_from_Transformer_for_Scene_Graph_Generation_CVPR_2024_paper.html) that tackled the challenge of dense prediction by proposing to compute a "relatedness" or "connectedness" score to prune pairs that are unlikely to have a relation, before the relation prediction stage. It generates a sparse set of pairs that can also run faster because as I explained [in my work](https://arxiv.org/abs/2405.16116), the quadratic complexity of relation prediction is one of the major bottlenecks for real-time SGG. However, generating sparse proposals was not the first aim of my work so I didn't implement it here, but you could probably try it on your own to solve your problem.

Thank you again for your reply, your guidance has been very beneficial!

**Comment by Maelic** [comment]
No worries, good luck on your project and happy coding :rocket:
