### ISSUE TITLE
ModuleNotFoundError: No module named 'sgg_benchmark'

### ISSUE THREAD

**Issue by zihan-ye** [Maelic/SGG-Benchmark#6]
many thanks for your work. following readme I have install all the dependencies however, when I was trying the webcam_demo.py, I met the issue ModuleNotFoundError: No module named 'sgg_benchmark'. Do you know how should I fix this? many thanks!

PS D:\sgg_new\SGG-Benchmark>  python demo\webcam_demo.py --classes D:\sgg_new\SGG-Benchmark\test.json --config ./configs/VG150/baseline/e2e_relation_X_101_32_8_FPN_1x.yaml --weights D:\sgg_new\SGG-Benchmark\test.pth --tracking
Traceback (most recent call last):
  File "D:\sgg_new\SGG-Benchmark\demo\webcam_demo.py", line 4, in <module>
    from demo_model import SGG_Model
  File "D:\sgg_new\SGG-Benchmark\demo\demo_model.py", line 8, in <module>
    from sgg_benchmark.modeling.detector import build_detection_model
ModuleNotFoundError: No module named 'sgg_benchmark'

**Comment by zihan-ye** [comment]
one add-up is  I have already build the local package using 
python setup.py build develop

but still this error:
ModuleNotFoundError: No module named 'sgg_benchmark'

**Comment by Maelic** [comment]
Are you in the correct conda environment? Try `conda activate scene_graph_benchmark`

**Comment by zihan-ye** [comment]
yes, I am in the correct conda enviroment, weird...

**Comment by zihan-ye** [comment]
however, I tried several times, I used exactly the same settings as you provided, and tried several times to clone and set up a new enviroment, the problem 'ModuleNotFoundError' always exists.
maybe something relates to operation system? May I ask are you using Linux or Windows?

**Comment by Maelic** [comment]
I'm using exclusively Linux. If you're having trouble on windows, I would recommend to try a colab environment for instance.
